spring:
  application:
    name: premises-smart-be

  datasource:
    url: jdbc:mysql://localhost:3306/premises_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: "jAMjZGnJMNn3TQygRghqXbrn6pDMR/NUqRrNsSTAjpgBIxrn2aZUZxMPkUw4AxBAi3U10k7AK2wnBccVVh5Xpw=="
    expiration: 86400           # 24 gi?
    refresh-expiration: 604800  # 7 ngày (n?u còn dùng ch? khác)
  admin:
    email: thangdc.tech@gmail.com
    password: 123456
    full-name: System Admin
    phone: "0912345678"



server:
  port: 8080
